export const skillsData=[
    {
        label:"FRONT END",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"50",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
            {
                skillName:"RRACTJS",
                percentage:"80",
            },
        ],
    },
    {
        label:"BACK END",
        data:[
            {
                skillName:"NODEJS",
                percentage:"90",
            },
            {
                skillName:"EXPRESSJS",
                percentage:"90",
            },
            {
                skillName:"API",
                percentage:"90",
            },
        ],
    },
    {
        label:"DATA-BASE",
        data:[
            {
                skillName:"MYSQL",
                percentage:"90",
            },
            {
                skillName:"MONGODB",
                percentage:"90",
            },
        ],
    },
]