export const skillsData=[
    {
        label:"FRONT END",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"50",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
        ],
    },
    {
        label:"BACK END",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"HTML",
                percentage:"90",
            },
        ],
    },
    {
        label:"FRONT END",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"HTML",
                percentage:"90",
            },
        ],
    },
]